# Generated by Django 3.1.5 on 2021-02-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zokusei', models.CharField(max_length=50, verbose_name='属性')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性',
            },
        ),
        migrations.CreateModel(
            name='Eligible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('shimei', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('shozoku', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('shokui', models.CharField(blank=True, max_length=50, null=True, verbose_name='職位')),
                ('nendo', models.IntegerField(verbose_name='実施年度')),
                ('bikou', models.CharField(max_length=200, verbose_name='備考')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.attribute')),
            ],
            options={
                'verbose_name': '対象者',
                'verbose_name_plural': '対象者',
            },
        ),
    ]
