# Generated by Django 3.1.4 on 2020-12-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='zokusei',
        ),
        migrations.RenameField(
            model_name='eligible',
            old_name='eligible',
            new_name='attribute',
        ),
    ]
