# Generated by Django 3.1.5 on 2021-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('shimei', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('shozoku', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('shokui', models.CharField(blank=True, max_length=50, null=True, verbose_name='職位')),
                ('nendo', models.IntegerField(verbose_name='年度')),
                ('uketsukebi', models.DateField(verbose_name='受付日')),
                ('kanryoubi', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('shutantou', models.CharField(blank=True, max_length=50, null=True, verbose_name='主担当')),
                ('fukutantou', models.CharField(blank=True, max_length=50, null=True, verbose_name='副担当')),
                ('haibunkikan', models.CharField(max_length=50, verbose_name='配分機関')),
                ('koubomei', models.CharField(max_length=200, verbose_name='公募名')),
                ('saihi', models.CharField(choices=[('0', ''), ('1', '採択'), ('2', '不採択'), ('9', '応募なし')], max_length=1, verbose_name='採否')),
            ],
            options={
                'verbose_name': '競争的研究資金申請支援',
                'verbose_name_plural': '競争的研究資金申請支援',
            },
        ),
        migrations.CreateModel(
            name='Kakenhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('shimei', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('shozoku', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('shokui', models.CharField(blank=True, max_length=50, null=True, verbose_name='職位')),
                ('nendo', models.IntegerField(verbose_name='年度')),
                ('uketsukebi', models.DateField(verbose_name='受付日')),
                ('kanryoubi', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('shutantou', models.CharField(blank=True, max_length=50, null=True, verbose_name='主担当')),
                ('fukutantou', models.CharField(blank=True, max_length=50, null=True, verbose_name='副担当')),
                ('shumoku', models.CharField(blank=True, max_length=50, verbose_name='研究種目')),
                ('saihi', models.CharField(choices=[('0', ''), ('1', '採択'), ('2', '不採択'), ('9', '応募なし')], max_length=1, verbose_name='採否')),
                ('bikou', models.CharField(blank=True, max_length=200, verbose_name='備考')),
            ],
            options={
                'verbose_name': '科研費申請書添削',
                'verbose_name_plural': '科研費申請書添削',
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('shimei', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('shozoku', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('shokui', models.CharField(blank=True, max_length=50, null=True, verbose_name='職位')),
                ('nendo', models.IntegerField(verbose_name='年度')),
                ('uketsukebi', models.DateField(verbose_name='受付日')),
                ('kanryoubi', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('shutantou', models.CharField(blank=True, max_length=50, null=True, verbose_name='主担当')),
                ('fukutantou', models.CharField(blank=True, max_length=50, null=True, verbose_name='副担当')),
            ],
            options={
                'verbose_name': 'マッチング支援',
                'verbose_name_plural': 'マッチング支援',
            },
        ),
    ]
