# Generated by Django 3.1.1 on 2020-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nayose_id', models.IntegerField(blank=True, null=True, verbose_name='名寄せID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('affiliation', models.CharField(max_length=50, verbose_name='所属')),
                ('fiscal_year', models.IntegerField(verbose_name='年度')),
                ('reception_date', models.DateField(verbose_name='受付日')),
                ('completion_date', models.DateField(verbose_name='完了日')),
                ('pic1', models.CharField(blank=True, max_length=50, verbose_name='主担当')),
                ('pic2', models.CharField(blank=True, max_length=50, verbose_name='副担当')),
                ('funding_agency', models.CharField(max_length=50, verbose_name='配分機関')),
                ('call_for_application', models.CharField(max_length=200, verbose_name='公募名')),
                ('judgement', models.CharField(choices=[(0, ''), (1, '採択'), (2, '不採択'), (9, '応募なし')], max_length=1, verbose_name='結果')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kakenhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nayose_id', models.IntegerField(blank=True, null=True, verbose_name='名寄せID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('affiliation', models.CharField(max_length=50, verbose_name='所属')),
                ('fiscal_year', models.IntegerField(verbose_name='年度')),
                ('reception_date', models.DateField(verbose_name='受付日')),
                ('completion_date', models.DateField(verbose_name='完了日')),
                ('pic1', models.CharField(blank=True, max_length=50, verbose_name='主担当')),
                ('pic2', models.CharField(blank=True, max_length=50, verbose_name='副担当')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='研究種目')),
                ('judgement', models.CharField(choices=[(0, ''), (1, '採択'), (2, '不採択'), (9, '応募なし')], max_length=1, verbose_name='結果')),
                ('remarks', models.CharField(blank=True, max_length=50, verbose_name='備考')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nayose_id', models.IntegerField(blank=True, null=True, verbose_name='名寄せID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('affiliation', models.CharField(max_length=50, verbose_name='所属')),
                ('fiscal_year', models.IntegerField(verbose_name='年度')),
                ('reception_date', models.DateField(verbose_name='受付日')),
                ('completion_date', models.DateField(verbose_name='完了日')),
                ('pic1', models.CharField(blank=True, max_length=50, verbose_name='主担当')),
                ('pic2', models.CharField(blank=True, max_length=50, verbose_name='副担当')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
