# Generated by Django 3.1.1 on 2020-09-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nayose_id', models.IntegerField(blank=True, null=True, verbose_name='名寄せID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('affiliation', models.CharField(max_length=50, verbose_name='所属')),
                ('fiscal_year', models.IntegerField(verbose_name='年度')),
                ('reception_date', models.DateField(verbose_name='受付日')),
                ('completion_date', models.DateField(verbose_name='完了日')),
                ('pic1', models.CharField(blank=True, max_length=50, verbose_name='主担当')),
                ('pic2', models.CharField(blank=True, max_length=50, verbose_name='副担当')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
