# Generated by Django 3.1.1 on 2020-09-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_inquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetitiveFunds',
            new_name='CompetitiveFund',
        ),
    ]
