# Generated by Django 3.1.1 on 2020-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20200922_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitivefund',
            name='nayose_id',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='nayose_id',
        ),
        migrations.RemoveField(
            model_name='kakenhi',
            name='nayose_id',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='nayose_id',
        ),
        migrations.AddField(
            model_name='competitivefund',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='名寄せID'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='名寄せID'),
        ),
        migrations.AddField(
            model_name='kakenhi',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='名寄せID'),
        ),
        migrations.AddField(
            model_name='matching',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='名寄せID'),
        ),
    ]
