# Generated by Django 3.1.1 on 2020-10-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20200922_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='fiscal_year',
            new_name='nendo',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='fiscal_year',
            new_name='nendo',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='fiscal_year',
            new_name='nendo',
        ),
        migrations.AlterField(
            model_name='competitivefund',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='eradcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号'),
        ),
    ]
