# Generated by Django 3.1.1 on 2020-10-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20201006_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitivefund',
            old_name='pic2',
            new_name='fukutantou',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='funding_agency',
            new_name='haibunkikan',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='completion_date',
            new_name='kanryoubi',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='call_for_application',
            new_name='koubomei',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='pic1',
            new_name='shutantou',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='reception_date',
            new_name='uketsukebi',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='remarks',
            new_name='bikou',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='pic2',
            new_name='fukutantou',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='completion_date',
            new_name='kanryoubi',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='category',
            new_name='shumoku',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='pic1',
            new_name='shutantou',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='reception_date',
            new_name='uketsukebi',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='pic2',
            new_name='fukutantou',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='completion_date',
            new_name='kanryoubi',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='pic1',
            new_name='shutantou',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='reception_date',
            new_name='uketsukebi',
        ),
        migrations.RemoveField(
            model_name='competitivefund',
            name='judgement',
        ),
        migrations.RemoveField(
            model_name='kakenhi',
            name='judgement',
        ),
        migrations.AddField(
            model_name='competitivefund',
            name='saihi',
            field=models.CharField(choices=[(0, ''), (1, '採択'), (2, '不採択'), (9, '応募なし')], default=1, max_length=1, verbose_name='採否'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kakenhi',
            name='saihi',
            field=models.CharField(choices=[(0, ''), (1, '採択'), (2, '不採択'), (9, '応募なし')], default='1', max_length=1, verbose_name='採否'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kakenhi',
            name='shubetsu',
            field=models.CharField(choices=[('1', '科研費個別支援'), ('2', '科研費チェックサポート'), ('3', 'その他')], default='1', max_length=1, verbose_name='性別'),
            preserve_default=False,
        ),
    ]
