# Generated by Django 3.1.1 on 2020-10-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20201006_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitivefund',
            old_name='name',
            new_name='shimei',
        ),
        migrations.RenameField(
            model_name='competitivefund',
            old_name='affiliation',
            new_name='shozoku',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='name',
            new_name='shimei',
        ),
        migrations.RenameField(
            model_name='kakenhi',
            old_name='affiliation',
            new_name='shozoku',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='name',
            new_name='shimei',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='affiliation',
            new_name='shozoku',
        ),
    ]
