# Generated by Django 3.1.1 on 2020-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20201006_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakenhi',
            name='shubetsu',
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='bikou',
            field=models.CharField(blank=True, max_length=200, verbose_name='備考'),
        ),
    ]
