# Generated by Django 3.1.1 on 2020-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20201006_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitivefund',
            name='fukutantou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='副担当'),
        ),
        migrations.AlterField(
            model_name='competitivefund',
            name='kanryoubi',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='competitivefund',
            name='saihi',
            field=models.CharField(choices=[('0', ''), ('1', '採択'), ('2', '不採択'), ('9', '応募なし')], max_length=1, verbose_name='採否'),
        ),
        migrations.AlterField(
            model_name='competitivefund',
            name='shutantou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主担当'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='fukutantou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='副担当'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='kanryoubi',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='saihi',
            field=models.CharField(choices=[('0', ''), ('1', '採択'), ('2', '不採択'), ('9', '応募なし')], max_length=1, verbose_name='採否'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='shutantou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主担当'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='fukutantou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='副担当'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='kanryoubi',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='shutantou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主担当'),
        ),
    ]
