# Generated by Django 3.1.4 on 2020-12-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20201006_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitivefund',
            options={'verbose_name': '競争的研究資金申請支援', 'verbose_name_plural': '競争的研究資金申請支援'},
        ),
        migrations.AlterModelOptions(
            name='kakenhi',
            options={'verbose_name': '科研費申請書添削', 'verbose_name_plural': '科研費申請書添削'},
        ),
        migrations.AlterModelOptions(
            name='matching',
            options={'verbose_name': 'マッチング支援', 'verbose_name_plural': 'マッチング支援'},
        ),
    ]
