# Generated by Django 3.1.5 on 2021-01-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20201207_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitivefund',
            name='shokui',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職位'),
        ),
        migrations.AddField(
            model_name='kakenhi',
            name='shokui',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職位'),
        ),
        migrations.AddField(
            model_name='matching',
            name='shokui',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職位'),
        ),
        migrations.AlterField(
            model_name='competitivefund',
            name='shimei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='competitivefund',
            name='shozoku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='shimei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='kakenhi',
            name='shozoku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='shimei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='shozoku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属'),
        ),
    ]
