# Generated by Django 3.1.5 on 2021-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='キーワード')),
                ('researcher_count', models.IntegerField(verbose_name='使用研究者数')),
                ('cumcount', models.IntegerField(verbose_name='のべ使用回数')),
            ],
            options={
                'verbose_name': 'キーワード',
                'verbose_name_plural': 'キーワード',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardnumber', models.CharField(max_length=255, verbose_name='課題番号')),
                ('title', models.CharField(max_length=255, verbose_name='課題名')),
                ('startfiscalyear', models.IntegerField(verbose_name='研究開始年度')),
                ('role', models.CharField(max_length=255, verbose_name='役割')),
                ('category_name', models.CharField(max_length=255, verbose_name='研究種目')),
                ('eradcode', models.CharField(max_length=8, verbose_name='研究者番号')),
                ('fullname', models.CharField(max_length=255, verbose_name='氏名')),
                ('institution', models.CharField(max_length=255, verbose_name='部局名')),
                ('department', models.CharField(max_length=255, verbose_name='部局名')),
                ('jobtitle', models.CharField(max_length=255, verbose_name='職名')),
                ('keywords', models.ManyToManyField(to='work.Keyword')),
            ],
            options={
                'verbose_name': '研究課題',
                'verbose_name_plural': '研究課題',
            },
        ),
    ]
