# Generated by Django 3.1.4 on 2020-12-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='催事名')),
                ('venue', models.CharField(max_length=50, verbose_name='会場')),
                ('kaisaibi', models.DateField(verbose_name='開催日')),
                ('nendo', models.IntegerField(verbose_name='開催年度')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('shimei', models.CharField(max_length=50, verbose_name='氏名')),
                ('shozoku', models.CharField(max_length=50, verbose_name='所属')),
                ('bikou', models.CharField(max_length=255, verbose_name='備考')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
            options={
                'verbose_name': '参加者',
                'verbose_name_plural': '参加者',
            },
        ),
    ]
