# Generated by Django 3.1.4 on 2020-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_presenter',
            field=models.CharField(choices=[('0', ''), ('1', '発表')], default=1, max_length=1, verbose_name='発表'),
            preserve_default=False,
        ),
    ]
