# Generated by Django 3.1.4 on 2020-12-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_attendee_is_presenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='bikou',
        ),
    ]
