# Generated by Django 3.1.4 on 2020-12-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_attendee_bikou'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='seminar',
            new_name='event',
        ),
    ]
