# Generated by Django 3.1.1 on 2020-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(max_length=8, verbose_name='研究者番号')),
                ('kanjishimei_sei', models.CharField(max_length=50, verbose_name='漢字氏名・姓')),
                ('kanjishimei_mei', models.CharField(max_length=50, verbose_name='漢字氏名・名')),
                ('kanashimei_sei', models.CharField(max_length=50, verbose_name='カナ氏名・姓')),
                ('kanashimei_mei', models.CharField(max_length=50, verbose_name='カナ氏名・名')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(max_length=1, verbose_name='性別')),
                ('department', models.CharField(max_length=50, verbose_name='部局名')),
                ('title', models.CharField(max_length=50, verbose_name='職位')),
            ],
        ),
    ]
