# Generated by Django 3.1.5 on 2021-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakushu_no', models.CharField(max_length=20, verbose_name='各種No')),
                ('kadai_id', models.CharField(max_length=20, verbose_name='課題ID')),
                ('oubo_saitaku_bangou', models.CharField(max_length=20, verbose_name='応募／採択番号')),
                ('nendo', models.IntegerField(verbose_name='年度')),
                ('seido_code', models.CharField(max_length=7, verbose_name='制度コード')),
                ('seidomei', models.CharField(max_length=200, verbose_name='制度名')),
                ('jigyoumei', models.CharField(max_length=200, verbose_name='事業名')),
                ('koubogroupmei', models.CharField(max_length=200, verbose_name='公募グループ名')),
                ('koubo_nendo', models.IntegerField(verbose_name='公募年度')),
                ('koubomei', models.CharField(max_length=200, verbose_name='公募名')),
                ('kadaimei', models.CharField(max_length=200, verbose_name='研究開発課題名')),
                ('kaishi_nendo', models.IntegerField(verbose_name='研究期間開始年度')),
                ('shuuryou_nendo', models.IntegerField(verbose_name='研究期間終了年度')),
                ('status', models.CharField(choices=[('1', '応募中'), ('2', '応募済'), ('3', '審査中'), ('4', '審査済'), ('5', '採択'), ('6', '不受理'), ('7', '取下げ'), ('8', '不採択（足切り）'), ('9', '不採択')], max_length=1, verbose_name='ステータス')),
                ('eradcode', models.CharField(max_length=8, verbose_name='研究者番号')),
                ('shimeikanji_sei', models.CharField(max_length=50, verbose_name='氏名漢字（姓）')),
                ('shimeikanji_mei', models.CharField(max_length=50, verbose_name='氏名漢字（名）')),
                ('kenkyuukikanmei', models.CharField(max_length=50, verbose_name='研究機関名')),
                ('bukyokumei', models.CharField(blank=True, max_length=50, null=True, verbose_name='部局名')),
                ('yakushoku', models.CharField(blank=True, max_length=50, null=True, verbose_name='役職')),
            ],
            options={
                'verbose_name': 'e-Rad応募データ',
                'verbose_name_plural': 'e-Rad応募データ',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('eradcode', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='研究者番号')),
                ('kenkyuushashimei_sei', models.CharField(max_length=50, verbose_name='研究者氏名-姓')),
                ('kenkyuushashimei_mei', models.CharField(max_length=50, verbose_name='研究者氏名-名')),
                ('furigana_sei', models.CharField(max_length=50, verbose_name='フリガナ-姓')),
                ('furigana_mei', models.CharField(max_length=50, verbose_name='フリガナ-名')),
                ('tsuushoumei_sei', models.CharField(blank=True, max_length=50, null=True, verbose_name='通称名-姓')),
                ('tsuushoumei_mei', models.CharField(blank=True, max_length=50, null=True, verbose_name='通称名-名')),
                ('tsuushoumeifurigana_sei', models.CharField(blank=True, max_length=50, null=True, verbose_name='通称名フリガナ-姓')),
                ('tsuushoumeifurigana_mei', models.CharField(blank=True, max_length=50, null=True, verbose_name='通称名フリガナ-名')),
                ('eiji_sei', models.CharField(blank=True, max_length=50, null=True, verbose_name='英字-姓')),
                ('eiji_mei', models.CharField(blank=True, max_length=50, null=True, verbose_name='英字-名')),
                ('seinengappi', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('seibetsu', models.CharField(choices=[('0', ''), ('1', '男性'), ('2', '女性'), ('9', 'その他')], max_length=1, verbose_name='性別')),
                ('gakui', models.CharField(blank=True, max_length=50, null=True, verbose_name='学位')),
                ('gakuishutokunengappi', models.CharField(blank=True, max_length=50, null=True, verbose_name='学位取得年月日')),
                ('bukyokumei', models.CharField(max_length=50, verbose_name='部局名')),
                ('shokumei', models.CharField(max_length=50, verbose_name='職位')),
                ('mailaddress1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス1')),
                ('mailaddress2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス2')),
                ('kakenhiouboshikaku', models.CharField(max_length=1, verbose_name='科研費応募資格')),
                ('shutarukenkyuukikan', models.CharField(max_length=1, verbose_name='主たる研究機関')),
                ('bukyokuchakuninbi', models.DateField(blank=True, null=True, verbose_name='部局着任日')),
                ('bukyokutaininbi', models.DateField(blank=True, null=True, verbose_name='部局退任日')),
                ('kanjishimei', models.CharField(max_length=100, verbose_name='研究者氏名')),
                ('kanashimei', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('tsuushoumei', models.CharField(blank=True, max_length=100, null=True, verbose_name='通称名')),
                ('tsuushoumei_kana', models.CharField(blank=True, max_length=50, null=True, verbose_name='通称名フリガナ')),
                ('eijishimei', models.CharField(blank=True, max_length=100, null=True, verbose_name='英字氏名')),
            ],
            options={
                'verbose_name': 'e-Rad研究者データ',
                'verbose_name_plural': 'e-Rad研究者データ',
            },
        ),
    ]
