# Generated by Django 3.1.1 on 2020-10-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0002_auto_20201005_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='id',
        ),
        migrations.AlterField(
            model_name='researcher',
            name='eradcode',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='研究者番号'),
        ),
    ]
