# Generated by Django 3.1.1 on 2020-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0003_auto_20201005_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='eiji_mei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='英字-名'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='eiji_sei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='英字-姓'),
        ),
    ]
