# Generated by Django 3.1.1 on 2020-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0004_auto_20201005_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='gakuishutokunengappi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学位取得年月日'),
        ),
    ]
