# Generated by Django 3.1.1 on 2020-10-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0005_auto_20201005_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='kijunbi',
            field=models.DateField(default=datetime.date(2020, 9, 3), verbose_name='基準日'),
            preserve_default=False,
        ),
    ]
