# Generated by Django 3.1.1 on 2020-10-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0006_researcher_kijunbi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='kijunbi',
            new_name='datashutokubi',
        ),
    ]
