# Generated by Django 3.1.1 on 2020-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0007_auto_20201005_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakushu_no', models.CharField(max_length=20, verbose_name='各種No')),
                ('kadai_id', models.CharField(max_length=20, verbose_name='課題ID')),
                ('oubo_saitaku_bangou', models.CharField(max_length=20, verbose_name='応募／採択番号')),
                ('nendo', models.IntegerField(verbose_name='年度')),
                ('seido_code', models.CharField(max_length=7, verbose_name='制度コード')),
                ('seidomei', models.CharField(max_length=200, verbose_name='制度名')),
                ('jigyoumei', models.CharField(max_length=200, verbose_name='事業名')),
                ('koubogroupmei', models.CharField(max_length=200, verbose_name='公募グループ名')),
                ('koubo_nendo', models.IntegerField(verbose_name='公募年度')),
                ('koubomei', models.CharField(max_length=200, verbose_name='公募名')),
                ('kadaimei', models.CharField(max_length=200, verbose_name='研究開発課題名')),
                ('kaishi_nendo', models.IntegerField(verbose_name='研究期間開始年度')),
                ('shuuryou_nendo', models.IntegerField(verbose_name='研究期間終了年度')),
                ('status', models.CharField(choices=[('5', '採択'), ('9', '不採択')], max_length=1, verbose_name='ステータス')),
                ('eradcode', models.CharField(max_length=8, verbose_name='研究者番号')),
                ('datashutokubi', models.DateField(verbose_name='データ取得日')),
            ],
        ),
        migrations.AlterField(
            model_name='researcher',
            name='datashutokubi',
            field=models.DateField(verbose_name='データ取得日'),
        ),
    ]
