# Generated by Django 3.1.1 on 2020-10-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0008_auto_20201005_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='datashutokubi',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='datashutokubi',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('1', '応募中'), ('2', '応募済'), ('3', '審査中'), ('4', '審査済'), ('5', '採択'), ('6', '不受理'), ('7', '取下げ'), ('8', '不採択（足切り）'), ('9', '不採択')], max_length=1, verbose_name='ステータス'),
        ),
    ]
