# Generated by Django 3.1.1 on 2020-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0009_auto_20201006_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': '応募データ', 'verbose_name_plural': '応募データ'},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'verbose_name': '研究者データ', 'verbose_name_plural': '研究者データ'},
        ),
        migrations.AddField(
            model_name='researcher',
            name='bukyokuchakuninbi',
            field=models.DateField(blank=True, null=True, verbose_name='部局着任日'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='bukyokutaininbi',
            field=models.DateField(blank=True, null=True, verbose_name='部局退任日'),
        ),
    ]
