# Generated by Django 3.1.1 on 2020-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0010_auto_20201028_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='seinengappi',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
