# Generated by Django 3.1.1 on 2020-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0013_auto_20201129_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bukyokumei',
        ),
        migrations.AddField(
            model_name='application',
            name='bukyokumei',
            field=models.CharField(default=1, max_length=50, verbose_name='部局名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='kenkyuukikanmei',
            field=models.CharField(default=1, max_length=50, verbose_name='研究機関名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='shimeikanji_mei',
            field=models.CharField(default=1, max_length=50, verbose_name='氏名漢字（名）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='shimeikanji_sei',
            field=models.CharField(default=1, max_length=50, verbose_name='氏名漢字（姓）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='yakushoku',
            field=models.CharField(default=1, max_length=50, verbose_name='役職'),
            preserve_default=False,
        ),
    ]
