# Generated by Django 3.1.5 on 2021-02-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nendo', models.IntegerField(verbose_name='年度')),
                ('kadaimei', models.CharField(max_length=200, verbose_name='課題名')),
                ('kubun', models.CharField(choices=[('1', '新規'), ('2', '継続')], max_length=1, verbose_name='区分')),
                ('saihi', models.CharField(choices=[('1', '採択'), ('2', '不採択'), ('3', '追加採択')], max_length=1, verbose_name='採否')),
                ('kiboukenkyuuhi', models.IntegerField(verbose_name='希望研究費')),
                ('haibunkingaku', models.IntegerField(verbose_name='配分金額')),
                ('bikou', models.CharField(max_length=200, verbose_name='備考')),
            ],
            options={
                'verbose_name': '課題名',
                'verbose_name_plural': '課題名',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('shimei', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('shozoku', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('shokui', models.CharField(blank=True, max_length=50, null=True, verbose_name='職位')),
                ('shokumei', models.CharField(max_length=50, verbose_name='職名')),
                ('nenrei', models.IntegerField(verbose_name='年齢')),
                ('seibetsu', models.CharField(choices=[('0', ''), ('1', '男性'), ('2', '女性'), ('9', 'その他')], max_length=1, verbose_name='性別')),
                ('role', models.CharField(choices=[('1', '代表'), ('2', '分担'), ('9', 'その他')], max_length=1, verbose_name='役割')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grant.project')),
            ],
            options={
                'verbose_name': '申請者',
                'verbose_name_plural': '申請者',
            },
        ),
    ]
