# Generated by Django 3.1.1 on 2020-10-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='haibunkingaku',
            field=models.IntegerField(default=0, verbose_name='配分金額'),
            preserve_default=False,
        ),
    ]
