# Generated by Django 3.1.1 on 2020-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0002_project_haibunkingaku'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kiboukenkyuuhi',
            field=models.IntegerField(default=0, verbose_name='希望研究費'),
            preserve_default=False,
        ),
    ]
