# Generated by Django 3.1.1 on 2020-10-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0003_project_kiboukenkyuuhi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_keizoku',
        ),
        migrations.AddField(
            model_name='project',
            name='kubun',
            field=models.CharField(choices=[('1', '新規'), ('2', '継続')], default=1, max_length=1, verbose_name='区分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('1', '代表'), ('2', '分担'), ('9', 'その他')], max_length=1, verbose_name='役割'),
        ),
        migrations.AlterField(
            model_name='project',
            name='saihi',
            field=models.CharField(choices=[('1', '採択'), ('2', '不採択'), ('3', '追加採択')], max_length=1, verbose_name='採否'),
        ),
    ]
