# Generated by Django 3.1.4 on 2020-12-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0004_auto_20201012_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '申請者', 'verbose_name_plural': '申請者'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '課題名', 'verbose_name_plural': '課題名'},
        ),
    ]
