# Generated by Django 2.2.12 on 2020-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nayose',
            fields=[
                ('nayose_id', models.AutoField(primary_key=True, serialize=False, verbose_name='名寄せID')),
                ('kanjishimei_sei', models.CharField(max_length=255, verbose_name='漢字氏名・姓')),
                ('kanjishimei_mei', models.CharField(max_length=255, verbose_name='漢字氏名・名')),
                ('kanashimei_sei', models.CharField(max_length=255, verbose_name='カナ氏名・姓')),
                ('kanashimei_mei', models.CharField(max_length=255, verbose_name='カナ氏名・名')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(choices=[(0, ''), (1, '男性'), (2, '女性'), (9, 'その他')], max_length=1, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Shokuin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shokuin_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='職員番号')),
                ('nayose_id', models.ManyToManyField(to='nayose.Nayose')),
            ],
        ),
        migrations.CreateModel(
            name='Erad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erad_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='研究者番号')),
                ('nayose_id', models.ManyToManyField(to='nayose.Nayose')),
            ],
        ),
    ]
