# Generated by Django 3.1.1 on 2020-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kijunbi', models.DateField(verbose_name='基準日')),
                ('eradcode', models.CharField(max_length=8, verbose_name='研究者番号')),
                ('kanjishimei_sei', models.CharField(max_length=50, verbose_name='漢字氏名・姓')),
                ('kanjishimei_mei', models.CharField(max_length=50, verbose_name='漢字氏名・名')),
                ('kanashimei_sei', models.CharField(max_length=50, verbose_name='カナ氏名・姓')),
                ('kanashimei_mei', models.CharField(max_length=50, verbose_name='カナ氏名・名')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(max_length=1, verbose_name='性別')),
                ('department', models.CharField(max_length=50, verbose_name='部局名')),
                ('title', models.CharField(max_length=50, verbose_name='職位')),
            ],
        ),
        migrations.CreateModel(
            name='Nayose',
            fields=[
                ('nayose_id', models.AutoField(primary_key=True, serialize=False, verbose_name='名寄せID')),
                ('erad_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='研究者番号')),
                ('shokuin_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='職員番号（常勤）')),
                ('hijoukin_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='職員番号（非常勤）')),
                ('kanjishimei_sei', models.CharField(max_length=30, verbose_name='漢字氏名（姓）')),
                ('kanjishimei_mei', models.CharField(max_length=30, verbose_name='漢字氏名（名）')),
                ('kanashimei_sei', models.CharField(max_length=30, verbose_name='カナ氏名（姓）')),
                ('kanashimei_mei', models.CharField(max_length=30, verbose_name='カナ氏名（名）')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(choices=[('0', ''), ('1', '男性'), ('2', '女性'), ('9', 'その他')], max_length=1, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Shokuin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kijunbi', models.DateField(verbose_name='基準日')),
                ('shokuin_id', models.CharField(max_length=8, verbose_name='職員番号')),
                ('shozokumei', models.CharField(max_length=50, verbose_name='所属名')),
                ('kakarikouzamei', models.CharField(blank=True, max_length=50, verbose_name='係講座名')),
                ('shokumei', models.CharField(blank=True, max_length=50, verbose_name='職名')),
                ('kanjishimei', models.CharField(max_length=50, verbose_name='漢字氏名')),
                ('furigana', models.CharField(max_length=50, verbose_name='フリガナ')),
                ('naisenbangou', models.CharField(blank=True, max_length=10, verbose_name='内線番号')),
                ('mail_address', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
            ],
        ),
    ]
