# Generated by Django 3.1.5 on 2021-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nayose',
            fields=[
                ('nayose_id', models.AutoField(primary_key=True, serialize=False, verbose_name='名寄せID')),
                ('eradcode', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='研究者番号')),
                ('shokuincode', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='職員番号（常勤）')),
                ('hijoukincode', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='職員番号（非常勤）')),
                ('kanjishimei_sei', models.CharField(max_length=30, verbose_name='漢字氏名（姓）')),
                ('kanjishimei_mei', models.CharField(max_length=30, verbose_name='漢字氏名（名）')),
                ('kanashimei_sei', models.CharField(max_length=30, verbose_name='カナ氏名（姓）')),
                ('kanashimei_mei', models.CharField(max_length=30, verbose_name='カナ氏名（名）')),
                ('seinengappi', models.DateField(verbose_name='生年月日')),
                ('seibetsu', models.CharField(choices=[('0', ''), ('1', '男性'), ('2', '女性'), ('9', 'その他')], max_length=1, verbose_name='性別')),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='ORCID')),
            ],
            options={
                'verbose_name': '名寄せデータ',
                'verbose_name_plural': '名寄せデータ',
            },
        ),
    ]
