# Generated by Django 3.1.1 on 2020-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nayose', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Erad',
        ),
        migrations.DeleteModel(
            name='Shokuin',
        ),
        migrations.AlterModelOptions(
            name='nayose',
            options={'verbose_name': '名寄せデータ', 'verbose_name_plural': '名寄せデータ'},
        ),
        migrations.RenameField(
            model_name='nayose',
            old_name='sex',
            new_name='seibetsu',
        ),
        migrations.RenameField(
            model_name='nayose',
            old_name='date_of_birth',
            new_name='seinengappi',
        ),
        migrations.AddField(
            model_name='nayose',
            name='orcid',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='ORCID'),
        ),
    ]
