# Generated by Django 3.1.1 on 2020-10-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nayose', '0002_auto_20201008_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nayose',
            old_name='erad_id',
            new_name='eradcode',
        ),
    ]
