# Generated by Django 3.1.1 on 2020-10-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nayose', '0003_auto_20201008_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nayose',
            old_name='hijoukin_id',
            new_name='hijoukincode',
        ),
        migrations.RenameField(
            model_name='nayose',
            old_name='shokuin_id',
            new_name='shokuincode',
        ),
    ]
