# Generated by Django 3.1.1 on 2020-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nayose', '0004_auto_20201008_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nayose',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='ORCID'),
        ),
    ]
